# Generated by Django 3.1.6 on 2021-04-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('cust_image', models.ImageField(db_column='Photo_customer', upload_to='')),
                ('cardcompany', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Rupay', 'Rupay'), ('NA', 'NA')], default='NA', max_length=10)),
                ('typeofCust', models.BooleanField(db_column='cust_type')),
                ('age', models.IntegerField(db_column='Age')),
                ('opening_date', models.DateField(db_column='openingDate')),
                ('balance_left', models.FloatField(db_column='Balance')),
                ('email', models.EmailField(db_column='Email', max_length=60)),
                ('phno', models.CharField(db_column='Ph_number', max_length=20)),
                ('Address', models.TextField(db_column='Address')),
                ('Type_loans', models.TextField()),
            ],
            options={
                'db_table': 'bankingsystem',
            },
        ),
    ]
